# Tutor AI Agent configuration
#
# Copy this file to ~/.computor/tutor.yaml (same directory as config.yaml)
# This file configures the tutor agent behavior, triggers, and strategies.

# Personality configuration - how the tutor presents itself
personality:
  name: "Tutor AI"
  tone: "friendly_professional"  # friendly_professional, strict, casual, encouraging
  language: "en"  # ISO 639-1 language code
  # custom_system_prompt_prefix: "You are a helpful assistant..."
  # custom_system_prompt_suffix: "Always be encouraging."

# Security configuration - threat detection and blocking
security:
  enabled: true
  require_confirmation: true  # Use 2nd LLM call to confirm threats
  block_on_threat: true       # Block response if threat confirmed
  check_messages: true        # Check student messages for prompt injection
  check_code: true            # Check code for malicious content
  # threat_log_path: /var/log/computor/threats.log

# Context configuration - what information to include
context:
  include_previous_messages: 3  # Number of previous messages (0-20)
  include_course_member_comments: true
  include_reference_solution: false
  max_code_lines: 1000
  max_code_files: 20
  # Student notes (optional)
  student_notes_enabled: false
  # student_notes_dir: /var/lib/computor/student-notes

# Grading configuration - automated grade assignment
grading:
  enabled: false
  auto_submit_grade: false  # POST grade to API automatically
  default_status: 0         # 0=NOT_REVIEWED, 1=CORRECTED, 2=CORRECTION_NECESSARY, 3=IMPROVEMENT_POSSIBLE
  require_human_review: true
  min_grade: 0.0
  max_grade: 1.0

# Trigger configuration - when the agent responds
# The agent uses tags in message titles to determine when to respond.
# Format: #scope::value (e.g., #ai::request)
# Triggers are automatically enabled when request_tags are defined.
# Set enabled: false explicitly to disable even with tags defined.
triggers:
  # Tags that trigger the agent to respond
  # Students add these to their message title to request AI help
  request_tags:
    - scope: "ai"
      value: "request"
    # - scope: "tutor"
    #   value: "help"

  # Tag added to agent responses (prevents duplicate responses)
  response_tag:
    scope: "ai"
    value: "response"

  # Also trigger on submission artifacts with submit=True
  check_submissions: true

  # If true, message must have ALL request_tags. If false, ANY tag triggers.
  require_all_tags: false

# Strategy configuration - per-intent settings
strategies:
  question_example:
    enabled: true
    max_response_tokens: 1000
    temperature: 0.7

  question_howto:
    enabled: true
    max_response_tokens: 1000
    temperature: 0.7

  help_debug:
    enabled: true
    max_response_tokens: 1500
    temperature: 0.5

  help_review:
    enabled: true
    max_response_tokens: 1500
    temperature: 0.5

  submission_review:
    enabled: true
    max_response_tokens: 2000
    temperature: 0.5

  clarification:
    enabled: true
    max_response_tokens: 800
    temperature: 0.7

  other:
    enabled: true
    max_response_tokens: 1000
    temperature: 0.7
